### ISSUE TITLE
Tool items are not available in workshop UI if they're placed into stash

### ISSUE THREAD

**Issue by Anrock** [Aoldri/anomaly-hf#3]
1. Put basic tools (or other) into workshop stash
2. Use workshop

Expected: can craft items that require basic tools
Actual: workshop status tab lists basic tools as absent
Workaround: grab tools from stash before using workshop

**Comment by Aoldri** [comment]
Could not reproduce on vanilla install.

**Comment by Anrock** [comment]
Apparently either old fixed issue or EFP specific.
